<a href="https://colab.research.google.com/github/nikenira/text-processing-sederhana/blob/main/Tugas1TP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
pip install nltk

In [ ]:
import nltk
nltk.download('punkt')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


True

In [ ]:
pip install Sastrawi

Import Library

In [ ]:
from nltk.tokenize import RegexpTokenizer
from Sastrawi.StopWordRemover.StopWordRemoverFactory import StopWordRemoverFactory
from Sastrawi.Stemmer.StemmerFactory import StemmerFactory

Dataset

In [ ]:
dataset = {}
dataset["D1"] = "lari lari pagi itu bikin sehat, badan sehat itu penting.\n"
dataset["D2"] = "pagi pagi kok sudah lari pagi\n"
dataset["D3"] = "korupsi akan sulit hilang, karena korupsi sudah jadi budaya\n"
dataset["D4"] = "agar sehat harus banyak lari lari pagi\n"
dataset["D5"] = "hobi kita korupsi ,budaya ya budaya\n"

Case Folding

In [ ]:
for k in dataset.keys():
  hasil_case_folding = dataset[k].lower()
  dataset[k] = hasil_case_folding
  print(dataset)

{'D1': 'lari lari pagi itu bikin sehat, badan sehat itu penting.\n', 'D2': 'pagi pagi kok sudah lari pagi\n', 'D3': 'korupsi akan sulit hilang, karena korupsi sudah jadi budaya\n', 'D4': 'agar sehat harus banyak lari lari pagi\n', 'D5': 'hobi kita korupsi ,budaya ya budaya\n'}
{'D1': 'lari lari pagi itu bikin sehat, badan sehat itu penting.\n', 'D2': 'pagi pagi kok sudah lari pagi\n', 'D3': 'korupsi akan sulit hilang, karena korupsi sudah jadi budaya\n', 'D4': 'agar sehat harus banyak lari lari pagi\n', 'D5': 'hobi kita korupsi ,budaya ya budaya\n'}
{'D1': 'lari lari pagi itu bikin sehat, badan sehat itu penting.\n', 'D2': 'pagi pagi kok sudah lari pagi\n', 'D3': 'korupsi akan sulit hilang, karena korupsi sudah jadi budaya\n', 'D4': 'agar sehat harus banyak lari lari pagi\n', 'D5': 'hobi kita korupsi ,budaya ya budaya\n'}
{'D1': 'lari lari pagi itu bikin sehat, badan sehat itu penting.\n', 'D2': 'pagi pagi kok sudah lari pagi\n', 'D3': 'korupsi akan sulit hilang, karena korupsi sudah j

Tokenizing


In [ ]:
tokenizer = RegexpTokenizer(r'\w+')
for k in dataset.keys():
  tokens = tokenizer.tokenize(dataset[k])
  dataset[k] = tokens
  print(dataset)

{'D1': ['lari', 'lari', 'pagi', 'itu', 'bikin', 'sehat', 'badan', 'sehat', 'itu', 'penting'], 'D2': 'pagi pagi kok sudah lari pagi\n', 'D3': 'korupsi akan sulit hilang, karena korupsi sudah jadi budaya\n', 'D4': 'agar sehat harus banyak lari lari pagi\n', 'D5': 'hobi kita korupsi ,budaya ya budaya\n'}
{'D1': ['lari', 'lari', 'pagi', 'itu', 'bikin', 'sehat', 'badan', 'sehat', 'itu', 'penting'], 'D2': ['pagi', 'pagi', 'kok', 'sudah', 'lari', 'pagi'], 'D3': 'korupsi akan sulit hilang, karena korupsi sudah jadi budaya\n', 'D4': 'agar sehat harus banyak lari lari pagi\n', 'D5': 'hobi kita korupsi ,budaya ya budaya\n'}
{'D1': ['lari', 'lari', 'pagi', 'itu', 'bikin', 'sehat', 'badan', 'sehat', 'itu', 'penting'], 'D2': ['pagi', 'pagi', 'kok', 'sudah', 'lari', 'pagi'], 'D3': ['korupsi', 'akan', 'sulit', 'hilang', 'karena', 'korupsi', 'sudah', 'jadi', 'budaya'], 'D4': 'agar sehat harus banyak lari lari pagi\n', 'D5': 'hobi kita korupsi ,budaya ya budaya\n'}
{'D1': ['lari', 'lari', 'pagi', 'itu',

Stopword by Sastrawi

In [ ]:
factory = StopWordRemoverFactory()
stopword_list=factory.get_stop_words()
for k in dataset.keys():
  tokens=[]
  for t in dataset[k]:
    if t not in stopword_list:
      tokens.append(t)
  dataset[k]=tokens
print(dataset)

{'D1': ['lari', 'lari', 'pagi', 'bikin', 'sehat', 'badan', 'sehat', 'penting'], 'D2': ['pagi', 'pagi', 'kok', 'lari', 'pagi'], 'D3': ['korupsi', 'sulit', 'hilang', 'korupsi', 'jadi', 'budaya'], 'D4': ['sehat', 'banyak', 'lari', 'lari', 'pagi'], 'D5': ['hobi', 'korupsi', 'budaya', 'budaya']}


Mencari Kata Uniq

In [ ]:
listku=list(dict.fromkeys(tokens))
print(listku)

['hobi', 'korupsi', 'budaya']


Import Library

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import euclidean_distances
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np
import pandas as pd
import operator

Bobot hanya frekuensi term dalam dokumen

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

In [ ]:
vectorizer = CountVectorizer()


In [ ]:
dataset = {}
dataset["D1"] = "lari lari pagi itu bikin sehat, badan sehat itu penting.\n"
dataset["D2"] = "pagi pagi kok sudah lari pagi\n"
dataset["D3"] = "korupsi akan sulit hilang, karena korupsi sudah jadi budaya\n"
dataset["D4"] = "agar sehat harus banyak lari lari pagi\n"
dataset["D5"] = "hobi kita korupsi ,budaya ya budaya\n"


X = vectorizer.fit_transform(dataset)
print(X)
print(X.toarray())
print(vectorizer.get_feature_names_out())
XT=X.transpose()
print(XT.toarray())



  (0, 0)	1
  (1, 1)	1
  (2, 2)	1
  (3, 3)	1
  (4, 4)	1
[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]
['d1' 'd2' 'd3' 'd4' 'd5']
[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


Bobot Menggunakan TF-IDF

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
print('KOLEKSI DOKUMEN :',dataset)
vectorizer=TfidfVectorizer(stop_words='english')
features=vectorizer.fit_transform(dataset)
print('TF-IDF :\n', features)
print(vectorizer.get_feature_names_out())
print(features.toarray().transpose())

KOLEKSI DOKUMEN : {'D1': 'lari lari pagi itu bikin sehat, badan sehat itu penting.\n', 'D2': 'pagi pagi kok sudah lari pagi\n', 'D3': 'korupsi akan sulit hilang, karena korupsi sudah jadi budaya\n', 'D4': 'agar sehat harus banyak lari lari pagi\n', 'D5': 'hobi kita korupsi ,budaya ya budaya\n'}
TF-IDF :
   (0, 0)	1.0
  (1, 1)	1.0
  (2, 2)	1.0
  (3, 3)	1.0
  (4, 4)	1.0
['d1' 'd2' 'd3' 'd4' 'd5']
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


Dataset

In [ ]:
dataset = {}
dataset["D1"] = "lari lari pagi itu bikin sehat, badan sehat itu penting.\n"
dataset["D2"] = "pagi pagi kok sudah lari pagi\n"
dataset["D3"] = "korupsi akan sulit hilang, karena korupsi sudah jadi budaya\n"
dataset["D4"] = "agar sehat harus banyak lari lari pagi\n"
dataset["D5"] = "hobi kita korupsi ,budaya ya budaya\n"
dataset["q"] = "lari pagi budaya"

Frekuensi Kemunculan Kata

In [ ]:
tf = CountVectorizer()
term_doc_matrix = tf.fit_transform(dataset.values())
pd.DataFrame(term_doc_matrix.toarray(), index=dataset.keys(), columns=tf.get_feature_names_out())

agar  akan  badan  banyak  bikin  budaya  harus  hilang  hobi  itu  ...  \
D1     0     0      1       0      1       0      0       0     0    2  ...   
D2     0     0      0       0      0       0      0       0     0    0  ...   
D3     0     1      0       0      0       1      0       1     0    0  ...   
D4     1     0      0       1      0       0      1       0     0    0  ...   
D5     0     0      0       0      0       2      0       0     1    0  ...   
q      0     0      0       0      0       1      0       0     0    0  ...   

    kita  kok  korupsi  lari  pagi  penting  sehat  sudah  sulit  ya  
D1     0    0        0     2     1        1      2      0      0   0  
D2     0    1        0     1     3        0      0      1      0   0  
D3     0    0        2     0     0        0      0      1      1   0  
D4     0    0        0     2     1        0      1      0      0   0  
D5     1    0        1     0     0        0      0      0      0   1  
q      0    0        0     1     1        0      0      0      0   0  

[6 rows x 22 columns]

Perhitungan Eucliden Distance

In [ ]:
ed = euclidean_distances(term_doc_matrix, term_doc_matrix)
df_ed=pd.DataFrame(ed, index=dataset.keys(), columns=dataset.keys())
df_ed

D1        D2        D3        D4        D5         q
D1  0.000000  4.242641  5.196152  3.316625  4.898979  3.605551
D2  4.242641  0.000000  4.582576  3.316625  4.472136  2.645751
D3  5.196152  4.582576  0.000000  4.472136  3.316625  3.464102
D4  3.316625  3.316625  4.472136  0.000000  4.123106  2.449490
D5  4.898979  4.472136  3.316625  4.123106  0.000000  2.645751
q   3.605551  2.645751  3.464102  2.449490  2.645751  0.000000

Pengurutan Ranking Euclidean Distance

In [ ]:
rank_ed={}
for k in dataset.keys():
  if k !="q":
    rank_ed[k]=df_ed.at[k,"q"]
top_rank_ed=dict(sorted(rank_ed.items(), key=operator.itemgetter(1)))
pd.DataFrame(top_rank_ed.values(),index=top_rank_ed.keys(), columns=["Euclidean Distance"])

Euclidean Distance
D4            2.449490
D2            2.645751
D5            2.645751
D3            3.464102
D1            3.605551

Pembobotan TF.IDF

In [ ]:
tfidf=TfidfVectorizer()
inverted_index=tfidf.fit_transform(dataset.values())
pd.DataFrame(inverted_index.toarray(), index=dataset.keys(), columns=tfidf.get_feature_names_out())

agar     akan     badan    banyak     bikin    budaya     harus  \
D1  0.000000  0.00000  0.295534  0.000000  0.295534  0.000000  0.000000   
D2  0.000000  0.00000  0.000000  0.000000  0.000000  0.000000  0.000000   
D3  0.000000  0.33631  0.000000  0.000000  0.000000  0.232831  0.000000   
D4  0.429054  0.00000  0.000000  0.429054  0.000000  0.000000  0.429054   
D5  0.000000  0.00000  0.000000  0.000000  0.000000  0.585654  0.000000   
q   0.000000  0.00000  0.000000  0.000000  0.000000  0.636460  0.000000   

     hilang     hobi       itu  ...     kita       kok   korupsi      lari  \
D1  0.00000  0.00000  0.591068  ...  0.00000  0.000000  0.000000  0.350656   
D2  0.00000  0.00000  0.000000  ...  0.00000  0.438867  0.000000  0.260362   
D3  0.33631  0.00000  0.000000  ...  0.00000  0.000000  0.551557  0.000000   
D4  0.00000  0.00000  0.000000  ...  0.00000  0.000000  0.000000  0.509080   
D5  0.00000  0.42297  0.000000  ...  0.42297  0.000000  0.346841  0.000000   
q   0.00000  0.00000  0.000000  ...  0.00000  0.000000  0.000000  0.545398   

        pagi   penting     sehat     sudah    sulit       ya  
D1  0.175328  0.295534  0.484684  0.000000  0.00000  0.00000  
D2  0.781086  0.000000  0.000000  0.359877  0.00000  0.00000  
D3  0.000000  0.000000  0.000000  0.275779  0.33631  0.00000  
D4  0.254540  0.000000  0.351830  0.000000  0.00000  0.00000  
D5  0.000000  0.000000  0.000000  0.000000  0.00000  0.42297  
q   0.545398  0.000000  0.000000  0.000000  0.00000  0.00000  

[6 rows x 22 columns]

Perhitungan Cosine Similarity

In [ ]:
cs = cosine_similarity(inverted_index,inverted_index)
df_cs = pd.DataFrame(cs, index=dataset.keys(), columns=dataset.keys())
df_cs

D1        D2        D3        D4        D5         q
D1  1.000000  0.228244  0.000000  0.393667  0.000000  0.286871
D2  0.228244  1.000000  0.099246  0.331363  0.000000  0.568004
D3  0.000000  0.099246  1.000000  0.000000  0.327661  0.148188
D4  0.393667  0.331363  0.000000  1.000000  0.000000  0.416477
D5  0.000000  0.000000  0.327661  0.000000  1.000000  0.372746
q   0.286871  0.568004  0.148188  0.416477  0.372746  1.000000

Pengurutan Ranking Cosine Similarity

In [ ]:
rank_cs = {}
for k in dataset.keys():
  if k !="q":
    rank_cs[k]=df_cs.at[k,"q"]
top_rank_cs = dict(sorted(rank_cs.items(), key=operator.itemgetter(1), reverse=True))
pd.DataFrame(top_rank_cs.values(), index=top_rank_cs.keys(), columns=["Cosine Similarity"])

Cosine Similarity
D2           0.568004
D4           0.416477
D5           0.372746
D1           0.286871
D3           0.148188